c/string_conversion.c
Have added a code for converting a Lowercase String to an Uppercase String with C.
=> String Lowercase to Uppercase

python/powers of 2.py
pls merge with hacktoberfest label
=> Create powers of 2.py

python/currenttime finder.py
pls merge with hacktoberfest label
=> Create currenttime finder.py

c/Circumference
=> Circumference

python/panda program.py
pls merge for hacktoberfest with label
=> Create panda program.py

c/SimpleInterest.c
Hey there, I have added a program to calculate Simple interest by taking rate, time and principal as inputs. Please accept my pull request.
=> Program to calculate Simple Interest

c/Power_using_function.c
Code to find the power using Function in C
=> Finding the power using Function

c/swap_with_pointer.c
Added a code to swap with the use of pointer in C
=> Swapping with the use of pointer

c/is_odd.c
is_odd.c  checks if a number is even or odd.
=> Add: is_odd.c added

c/Greatestnumber.c
Added a code to find the greatest number among four numbers.
=> Finding Greatest number  with C

.gitignore, CONTRIBUTING.md, c/is_odd.c, web/README.md
Added a .gitignore file which excludes c/python/java and vscode specific folders and files.
=> Added: .gitignore file added

c/power2_mod.c
power2_mod.c calculates the mod of powers of 2.
=> Add: power2_mod.c added

cpp/LexicographicalNumbers.cpp
I worked on the solution to the problem ,Given an integer n, return all the numbers in the range [1, n] sorted in lexicographical order,
Thank You for reading my pull request.
=> 'LexicographicalNumbers'

Counting.cpp
=> Bucket Sort

c/bogo_sort.c
=> Add: Bogosort.c

cpp/Krushkal.cpp
Working code of Krushkal Graph Algorithm for Minimum Spanning Tree
=> Krushkal Algorithm

python/snake.py
Add a Snake Game made in Python
=> Add Snake Game

README.md, python/Calculator.py
=> added Calculator.py 

c/isPalindrome.c, c/mergeSort.c
I have implemented the program for the given string is palindrome or not as per specified issue #208 .
please have a look at it.
=> Implement Palindrome program in C #208

python/Check.py, python/age.py, python/powers of 2.py
Using f-strings, enumerate, and inline conditions can increase the readability of code.
=> Refactoring

python/Fibbonacci_Series_Class.py, python/Paper_Rock_Scissor_Game.py
Objective: The goal of this task is to create the core logic for the Rock, Scissors, Paper game in Python. This includes handling user input, generating computer choices, determining the winner, and displaying the results. **using class based method**
this commit resolves #203
=> Paper_Rock_Scissor-Game resolves #203 

python/downward-triangle-pattern.py
Solved #216 ,
Added file downward-triangle-pattern.py in python directory.
=> Added python program downward-triangle-pattern.py 

cpp/Longest_Palindromic.cpp
Issue link: #220 
Q : you have given a string in which you have to find the longest palindromic substring and return it.
Also, please add the hacktoberfest2023 badge for nominating this for this year's hacktoberfest.
=> Added CPP Problem Longest Palindromic Substring

c/isPalindrome.c, c/mergeSort.c, java/constructorOverloading.java
Hi, I have implemented a common example of constructor Overloading in java.
please have a look. Thanks
=> Constructor Overloading in Java Implementation #213

cpp/MaxHeap.cpp
- Implemented Max Heap
- Simplified Max Heap code
- Easiest to understand
- Performs various operations
=> Created MaxHeap.cpp

python/Fibonacci_Series.py
Coded in a more Pythonic way and reduced the number of lines.
=> Shorter and readable code

cpp/sudoku_solver.cpp, data_structure/topological_sort.py, python/downward_traingle_pattern.py, python/fibonacci_series.py
=> Downward triangle/python

python/fibonacci_series.py
=> fibonacci code added

cpp/sudoku_solver.cpp, python/fibonacci_series.py
=> Suduko solver

cpp/sudoku_solver.cpp, data_structure/topological_sort.py, python/fibonacci_series.py
=> Topological

python/reverseString.py
Removed extra temp variable which was being used for swapping of elememts in list
=> Removed extra variable for swapping

python/Count_Sort.py
Removed extra for loop, used for loop instead of while loop and used f-strings for readability.
=> Code refactored and removed unecessary loops

java/threads.java
I have implemented threads in java. Please review it, Thanks :)
=> Implement Threads in Java #214

cpp/Banking system.cpp
This program simulates a simple banking system with account management features.
=> Banking system management.cpp

cpp/sudokusolver.cpp
Implemented Sudoku Solver . This is my first time with Open Source and Hacktoberfest so I would be really happy if you merge my contribution. Thank You!
=> Sudoku Solver

cpp/Binarysearch.cpp, data_structure/circular_queue.c, data_structure/tower_of_hanoi.c
Added the code of the problems using C
=> Added Tower Of Hanoi, Circular Queue Problem

java/towerOfHanoi.java
=> created tower of hanoi code in java

python/armstrong.py
=> Created  a code to check armstrong number

data_structure/double_linkedlist.py
I have added  the double linked_list code in python in the data-structure folder which was assigned to me. This PR contains that DSA problem of Double Linked list in python. Please review and merge.
=> Double linkedlist in python

java/toi.java
=> tower of hanoi

java/tower_of_hanoi.java
Add the Tower of Hanoi problem in JAVA . As assigned ,creating a new PR for tower of Hanoi problem in java.Please review and merge the code.
Tower of Hanoi is such a problem that involves moving a stack of disks from one peg to another following certain rules:
Rules are as follows:
1.Only one disk can be moved at a time
2.Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack. In other words, a disk can only be moved if it is the uppermost disk on a stack.
3.No larger disk may be placed on top of a smaller disk.
As assigned ,creating a new PR for tower of Hanoi problem in java.
=> Tower of hanoi in java

java/TreeTraversal.java
In this code I have traversed the tree with preorder , postorder and inorder traversal
=> TreeTraversal Implementation In Java

data_structure/Kadane's Algorithm.java
Hi , Added Kadane's Algorithm Code in Java .
Please add hackober fest  and hacktoberfest-accepted label . 
Thanks.
=> Implement Kadane's Algorithm Program in Java 

python/pascal's-triangle.py
Issue : Implement Pascal's Triangle Generation in Python #224
I added pascals-triangle program in python.
Please accept my PR for Hactoberfest2023.
=> pascal's-triangle.py added

python/Pascal's triangle in python.py
Code to create a pascals triangle implemented , I would like to register this one under hactoberfest
=> Create Pascal's triangle in python.py

java/Maximum Value of an Ordered Triplet I, java/Maximum Value of an Ordered Triplet I.java
add the problem Maximum Value of an Ordered Triplet I in Java language
=> Create Maximum Value of an Ordered Triplet I.java

cpp/sudoku_solveroptimum.cpp
Heyy I have added the sudoku solver in cpp can u let me know if there are any changes are to be done in the code
=> added sudoku solver

python/downward_triangle_pattern.py
Completed the downward triangle pattern in python as the task assigned under hacktobarfest23 under #216 . Please Review and merge the PR.
=> Downward Triangle Pattern in python

LeetCodeQuestions/557. Reverse Words in a String III/main.java
Added the folder as LeetCode Question and solved today's challenge #289
=> solved the daily checkin leetcode question 

web/Random-Code-Generator/css/normalize.css, web/Random-Code-Generator/css/styles.css, web/Random-Code-Generator/index.html, web/Random-Code-Generator/js/script.js
=> RandomCodeGenerator

HackerRank-Solutions/Python/arithmetic-operators.py, HackerRank-Solutions/Python/division.py, HackerRank-Solutions/Python/hello-world.py, HackerRank-Solutions/Python/if-else.py, HackerRank-Solutions/Python/loops.py
Hacktoberfest 2023 :)
https://www.hackerrank.com/domains/python/
will upload most of the solution soon.
=> HackerRank-Solutions [1-5]

cpp/binary_Search.cpp
Added binary search code in CPP
=> added binary search cpp

java/averageOfLevelsBT.java
Given the root of a binary tree, return the average value of the nodes on each level in the form of an array.
=> Created averageOfLevelsBT.java and added it to the Java folder

cpp/sudoku_solver_opt.cpp
added sudoku solver in cpp with integer vector as  a input for sudoku board
=> added sudoku solver in cpp

java/multithread.java, python/Bubble-Sort.py, python/downward_triangle_pattern.py
Added Bubble Sort written in Python
=> Added Bubble Sort

web/mini-calendar/index.html, web/mini-calendar/index.js, web/mini-calendar/style.css
=> MINICALENDAR

data_structure/mergeSort.java
implemented merge sort algorithm useful in sorting an array in time complexity of O(nlogn)
it works on divide and conquer algorithm
java file added
=> added merge sort algorithm in java

data_structure/avltree.cpp, python/downward_triangle_pattern.py
Added the code for creating an AVL tree in c++
=> Added the code for creating an AVL tree

python/Insertion-Sort.py
=> Added Insertion Sort

java/NQueens.java
Given an integer n, return all distinct solutions to the n-queens puzzle.
=> Added N-queens solution in to the java folder

README.md
=> resolve Add the list of contributors at the footer of the readme.md file hacktoberfest #239 

python/Merge-sort.py
=> Added Merge Sort

data_structure/graph.cpp
I added the c++ code for the implementation of graph data structure. Kindly review and merge it :).
=> added the code for implementation of graph

python/dsa-list.py
=> Added DSA-LIST

LeetCodeQuestions/letterCombinations.java
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent.
link - https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/
=> Create letterCombinations.java and added it to leetcode folder

data_structure/linked_list/removeNthNode.py, data_structure/linked_list/reverse_linkedlist.py
This pull request adds two new features to the repository:
1. Reverse Linked List Code:
- Implemented iterative approach to reverse a linked list.
- The code is available in the file `data_structure/linked_list/reverse_linkedlist.py`.
2. Remove Nth Node from end of the list Code:
- Implemented a function to efficiently remove the nth node from the end of a linked list using the two-pointer technique.
- The code is available in the file `data_structure/linked_list/removeNthNode.py`.
=> Feature: Add Reverse List and Remove Nth Node from end Code

c/binomial.c
This refactored version breaks out the probability calculation into its own function and avoids nested if-statements, which helps with readability and maintainability.
=> Updated binomial.c

data_structure/in_order_pre_order_and_post_order_traversal.c
added inorder,postorder,preorder tree traversal methods for hacktoberfest 2023
=> added all tree traversal methods in C

cpp/binary_search.cpp, cpp/graph.cpp
i have created binary search and graph in C++ all by my best of knowledge
=> binary search and graph implemented in C++

LeetCodeQuestions/15. 3sum.cpp, LeetCodeQuestions/31. Next Permutation.cpp
added solution for the leetcode qn 3sum in c++
=> added solution for 3sum in cpp

LeetCodeQuestions/HouseRobberIII.cpp
I have added optimized solution for HouseRobber III in LeetCode Questions folder
=> Add HouseRobberIII C++

cpp/checkArmStrong.cpp
check if any number is Armstrong number or not
=> Create checkArmStrong.cpp to check the armstrong number

cpp/numberDecrement.cpp
created a special pattern numberDecrememt.cpp in cpp folder  to follow the number's decrement in a specific pattern.
=> Created numberDecrement.cpp file

cpp/highest_lowest_frequency_with_hashing.cpp
Created highest_lowest_frequency_with_hashing.cpp at cpp folder to count the frequency of lowest and highest frequency elements.
=> Created highest_lowest_frequency_with_hashing.cpp

cpp/linearSearch.cpp
added linearSearch.cpp file in cpp folder to make the linear search in the array.
=> Created linearSearch.cpp

cpp/insertionSort.cpp
i have added an insertion sort code
=> Added insertion sort program in cpp

data_structure/TreeNode DS Usinng Java/Main.java, data_structure/TreeNode DS Usinng Java/TreeNode.java
Please Merge and Close the issue. As i have implemented a Data Structure Using Java. 
Thanks & Regards
=> Issue : Implement a Data Structure Using Java 

cpp/unionOfTwoArray.cpp
added file to create the union of two array elements in cpp.
=> Created unionOfTwoArray.cpp file in cpp folder

cpp/saddle.cpp
saddle point is -> min in row and max in column
application-> used in maps,social media
=> Program to find saddle point

cpp/Bookshop.cpp
Added a Program to be used in Bookshops to know the Stock Position and Price of books also calculate the total price during checkout and an option to add new books in Stock.
=> Added a Bookshop Program in Cpp to Buy Books and Add New Books

cpp/Stack using Template Function.cpp, data_structure/stack.c
Added a program that shows the implementation of stack using template class
=> Stack using Template Class

cpp/Symmetric_Butterfly_Pattern.cpp
added a cpp file to print a symmetric butterfly pattern in the cpp folder.
=> Created Symmetric_Butterfly_Pattern.cpp in cpp.

LeetCodeQuestions/Kadane'sAlgorithm.cpp
The Maximum Subarray Sum or the Kadane's Algorithm is a very well known problem across leetcode.
=> Added the code for Kadane'sAlgorithm or MaximumSubarraySum

data_structure/Subarray.cpp, data_structure/maxSumSubarray.cpp, data_structure/sumAllSubarray.cpp, web/Loding Kit/index.html, web/Loding Kit/style.css
1. All the possible subarrays and their respective sums.
2. No. of possible subarrays.
3. Max sum possible of a subarray.
=> DSA (Subarray based Ques.)

cpp/tictactoe1.cpp
I have built this game by using 2-D array only ,used best approach to build this game which makes it more simple and beautiful to play.
=> Tic Tac Toe game in cpp

OOPS/Constructors_Destructors.cpp, OOPS/Standard_Template_Library.cpp, OOPS/thisPointer_freindFunc_inlineFunc_defaultPara.cpp
I created OOPS folder and added some of the basic programs
closes #439
=> create OOPS folder

cpp/Two_Sum.cpp
=> Two Sum code added

python/A_star.py
=> solves issue #475

LeetCodeQuestions/minimum-ascii-delete-sum-for-two-strings.cpp, OOPS/Constructors_Destructors.cpp, OOPS/Standard_Template_Library.cpp, OOPS/thisPointer_freindFunc_inlineFunc_defaultPara.cpp
I have added optimized solution for leetcode question 'minimum-ascii-delete-sum-for-two-strings' in the Leetcode Questions folder
closes #442
=> Leetcode question

LeetCodeQuestions/Remove Duplicates from Sorted List.cpp
problem link : https://leetcode.com/problems/remove-duplicates-from-sorted-list/description/
=> Solution added for LeetCode problem : Remove Duplicates from Sorted List

cpp/specialindex2.cpp
special index-> if after deleting element from index i , sum of even index=sum of odd index approach->
after deleting ,previous element at odd index will be now at even index and vice versa s_odd= odd[0 to i]+ even[i+1 to len]
s_even=even[0 to i]+odd[i+1 to len]
=> Find special index in an array

LeetCodeQuestions/minimum-ascii-delete-sum-for-two-strings.cpp, python/Tkinter/Tkinter_1.py, python/Tkinter/Tkinter_2.py
I have created a folder named Tkinter inside Python folder and added basic tkinter programs.
closes #443
=> Basic Tkinter programs

HackerRank-Solutions/JavaScript/arithmetic-operators.js, HackerRank-Solutions/JavaScript/data-types.js, HackerRank-Solutions/JavaScript/function.js, HackerRank-Solutions/JavaScript/hello-world.js, HackerRank-Solutions/JavaScript/if-else.js, HackerRank-Solutions/JavaScript/let-and-const.js
=> JavaScript Solutions

web/ui-92-button/index.html, web/ui-92-button/style.css
It's website related to button fancy button design
Preview down below
=> Feat/website UI buttons

cpp/queues_implementation.cpp, cpp/stacks_implementation.cpp
* stacks functions like push,pop,top
* queues functions like enqueue,dequeue
=> Implementation of Stacks and Queues using arrays

cpp/binary_search.cpp, cpp/bubblesort.cpp
Made bubble sort algorithm using CPP.
=> Added Bubblesort using cpp

cpp/Bank.cpp
Bank Program that enables withdraw and deposit money options with service charges without a minimum balance and compound interest  option for savings account and chequebook facility for current account that can make transactions between accounts within the accounts
=> Added a Bank Program to Create Accounts and make Transactions

LeetCodeQuestions/75. Sort Colors/.idea/.gitignore, LeetCodeQuestions/75. Sort Colors/.idea/75. Sort Colors.iml, LeetCodeQuestions/75. Sort Colors/.idea/misc.xml, LeetCodeQuestions/75. Sort Colors/.idea/modules.xml, LeetCodeQuestions/75. Sort Colors/.idea/vcs.xml, LeetCodeQuestions/75. Sort Colors/SortColors.java, LeetCodeQuestions/75. Sort Colors/out/production/75. Sort Colors/.idea/.gitignore, LeetCodeQuestions/75. Sort Colors/out/production/75. Sort Colors/.idea/75. Sort Colors.iml, LeetCodeQuestions/75. Sort Colors/out/production/75. Sort Colors/.idea/misc.xml, LeetCodeQuestions/75. Sort Colors/out/production/75. Sort Colors/.idea/modules.xml, LeetCodeQuestions/75. Sort Colors/out/production/75. Sort Colors/.idea/vcs.xml
Added solution for question no 75. Sort Colorin Java with the brute and optimal approach by explaining both methods.
=> added 75. Sort Colors solution in java

cpp/vector.cpp
Performing different operations on vectors in cpp.
=> Operations on Vectors

c/pass.c
a C program to generate a random password involves generating random characters from a given character set and combining them to create a password
=> Initial Commit

LeetCodeQuestions/123_pattern.cpp
leetcode 123 pattern question added with explanation in c++
=>  leetcode 123 pattern question added with explanation

LeetCodeQuestions/Two_sum.cpp
Leetcode Two_sum Problem added with proper expanation
=>  Leetcode Two_sum Problem added with proper expanation

java/quick_sort.java
hey I have implemented quick Sort in Java as assigned in issue #209.
please have a look.
=> Implement a data structure program in java #209

LeetCodeQuestions/roman_to_integer.py
=> solved leetcode problem roman to integer

java/BFSofBinarySearchTree.java
Implemented BST for Binary Search Tree.
=> Added BSTofBinarySearchTree.java

python/Pascal's_Triangle.py
Added Pascal's_Triangle.py in the python folder.
=> Pascal's Triangle in Python , Issue: #224

java/bubblesort.java
=> bubble sort java

cpp/bitwise_operator.cpp
added all bitwise operators also added a program to swap two numbers using XOR
=> added bitwise operators addressing issue #405

LeetCodeQuestions/Regular-Expression-Matching.cpp
#444 Issue Resolved 
Please merge it with the main branch
=> Create  Regular-Expression-Matching.cpp

c/atm.c
C program that simulates a simple ATM (Automated Teller Machine) interface. It allows users to check their balance, deposit money, withdraw money, and exit the program. The user's account balance is stored as a variable in memory for simplicity.
=> Atm machine

LeetCodeQuestions/901. OnlineStockSpan.cpp, LeetCodeQuestions/Two_sum.cpp
Hello there,
I have added c++ code for leetcode question 901. Online Stock Span. This code has successfully passed all 99 testcases.
Thank You.
=> Added code for 901. Online Stock Span

c/atm.c, c/negativefac.c
C program that calculates the factorial of a given non-negative integer using recursion, This program takes a non-negative integer as input, calculates its factorial using a recursive function, and then displays the result. The factorial of a non-negative integer n is the product of all positive integers from 1 to n.
=> Branch2: Final Commit

LeetCodeQuestions/TopologicalSort.cpp
I have added the code for TopologicalSort using both BFS and DFS, this has been a standard question across the coding platforms like leetcode, gfg, etc.
=> Added the code for TopologicalSort

LeetCodeQuestions/Count Primes.cpp
=> Create Count Primes.cpp

c/Binary_Search_Trees.c, c/Binary_Trees.c, c/Djiktras_Algorithm.c, c/Double_Linked_List.c, c/Expression_Tree.c, c/Unordered_List.c
Hello, I mostly code in C
I have added programs for 
- Binary Tree
- Binary Search Tree
- Doubly Linked List
- Expression Tree
- Unordered List
Hope these can help people learning Data Structures in C
=> Added Data Structures made in C language

java/infixtopostfix.java
=> infix to postfix java

data_structure/linked_list/merge2lists.py, data_structure/linked_list/middleOfList.py
I have added Python programs for two common linked list operations:
1. Merging Two Lists:
- Implemented a function to merge two sorted linked lists into a single sorted list.
- The code is available in the file `data_structure/linked_list/merge2lists.py`.
2. Finding Middle of LinkedList:
- Implemented a function to find the middle node of a linked list. If the list has an even number of elements, it returns the second middle element.
- The code is available in the file `data_structure/linked_list/middleOfList.py`.
These additions address the concerns raised in issue #305
=> Added Python Programs for Merging two sorted Lists and Finding Middle of LinkedList

cpp/DiceGame.cpp
=> resolves #521

java/numberDecrement.java
added a java file in the java folder to create a number decrement pattern.
=> Created numberDecrement.java

cpp/Decode_Ways.cpp
Implemented Decode ways using cpp.
=> Added Decode_Ways.cpp

LeetCodeQuestions/remove_nth_node_from_end_of_linkedlist.cpp
Remove nth node form end of LinkedList added with proper expanation
=> Remove nth node form end of linkedlist added

java/insertionsort.java
=> insertion sort java

python/Tic Tac Toe.py
I'm a beginner to open Source please help and support me.
Thank you
=> python_File

cpp/Operator Overloading.cpp
Added a program showing  usage of the operator overloading feature of C++ to work with members of a class
=> Added a Program Showing Operator Overloading in c++

javascript/paginate.js
Hello, i would like to add helper sequelize pagination to repo
please kindly to reviewing my pull request
thank you
=> Add snippet helper sequelize pagination

cpp/4Sum explanation.cpp
In the 4Sum explanation.cpp file I have explained both brute force approach as well as Optimal Approach
=> Resolved issue #650 : Created a 4Sum explanation.cpp file 

data_structure/Stack/Delete_middle_element.cpp, data_structure/Stack/Mini_cost_to_make_string_valid.cpp, data_structure/Stack/Next_smaller_element.cpp, data_structure/Stack/Redundant_brackets.cpp, data_structure/Stack/Reverse_stack_using_recursion.cpp, data_structure/Stack/Reverse_string_using_stack.cpp, data_structure/Stack/Sort_stack.cpp, data_structure/Stack/Stack_using_array.cpp, data_structure/Stack/Stack_using_linkedList.cpp, data_structure/Stack/Valid_Parenthesis.cpp
Added the stack data structure and some practice questions of the stack.
=> Stack DataStructure added
